
package gbstore;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel dt;
    Statement st;
            
    int id, prix, stock, nTotal;
    String nomlivre, categorie, auteur, description = "";
    
    int menuState = 0;
    public Accueil() {
        initComponents();
        con = new JavaConnect().createConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(970, 680));
        setMinimumSize(new java.awt.Dimension(970, 680));
        setPreferredSize(new java.awt.Dimension(970, 680));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(249, 191, 33));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(218, 157, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 1(2).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(28, 30, 54, 54);

        jButton7.setBackground(new java.awt.Color(217, 87, 14));
        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Rechercher");
        jPanel1.add(jButton7);
        jButton7.setBounds(439, 117, 223, 59);

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel13.setText("Boutique");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(510, 36, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Galsen BookStore(2).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(116, 32, 323, 42);

        jPanel5.setBackground(new java.awt.Color(218, 157, 0));
        jPanel5.setLayout(null);

        jButton2.setBackground(new java.awt.Color(218, 157, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home 1(1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(22, 118, 64, 64);

        jButton3.setBackground(new java.awt.Color(218, 157, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/18635(1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(22, 535, 64, 64);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 0, 108, 616);
        jPanel5.setVisible(false);

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 610, 400);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(28, 196, 635, 420);

        jPanel3.setBackground(new java.awt.Color(40, 40, 40));
        jPanel3.setLayout(null);

        jButton9.setBackground(new java.awt.Color(217, 87, 14));
        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Afficher Panier");
        jPanel3.add(jButton9);
        jButton9.setBounds(10, 50, 142, 40);

        jButton10.setBackground(new java.awt.Color(217, 87, 14));
        jButton10.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Vider");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(160, 50, 77, 40);

        jButton11.setBackground(new java.awt.Color(217, 87, 14));
        jButton11.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Valider la Vente");
        jPanel3.add(jButton11);
        jButton11.setBounds(10, 250, 228, 67);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Monnaie :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 190, 90, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 191, 33));
        jLabel5.setText("1 element");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(120, 10, 100, 30);

        jTextField2.setBackground(new java.awt.Color(217, 87, 14));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("10000 frs");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(120, 150, 120, 30);

        jTextField3.setBackground(new java.awt.Color(146, 146, 146));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("60000 frs");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(120, 190, 120, 30);

        jTextField4.setBackground(new java.awt.Color(249, 191, 33));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("4000 frs");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField4);
        jTextField4.setBounds(120, 110, 120, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Panier :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 10, 70, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 110, 70, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Reçu :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 150, 70, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(680, 284, 253, 332);

        jPanel4.setBackground(new java.awt.Color(40, 40, 40));
        jPanel4.setLayout(null);

        jButton8.setBackground(new java.awt.Color(217, 87, 14));
        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Ajouter");
        jPanel4.add(jButton8);
        jButton8.setBounds(130, 170, 100, 40);

        jButton12.setBackground(new java.awt.Color(217, 87, 14));
        jButton12.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("+ d'infos");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(20, 170, 100, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Titre : ");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(12, 20, 80, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Catégorie : ");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(12, 80, 93, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 191, 33));
        jLabel6.setText("La belle histoire de Leuk-le-Lièvre ");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(80, 10, 150, 50);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 191, 33));
        jLabel7.setText("Conte");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(110, 80, 130, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prix : ");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(12, 120, 80, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 191, 33));
        jLabel9.setText("4000 frs");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(110, 120, 130, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(680, 32, 253, 229);

        jTextField1.setBackground(new java.awt.Color(40, 40, 40));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(28, 117, 396, 59);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(menuState == 0){
    jPanel5.setVisible(true);
    menuState = 1;
    }else{
    jPanel5.setVisible(false);
    menuState = 0;
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            
        try {
            st = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
            dt = new DefaultTableModel();
            
            
            dt.addColumn("id");
            dt.addColumn("Nom livre");
            dt.addColumn("Categorie");
            dt.addColumn("Auteur");
            dt.addColumn("Description");
            dt.addColumn("Prix");
            dt.addColumn("Stock");
            jTable1.setModel(dt);


             try {
            dt.setRowCount(0);
                rs = st.executeQuery("select * from livres ");
                
            while (rs.next()) {
                nTotal++;
                id = rs.getInt("id");
                nomlivre = rs.getString("nomlivre");
                categorie = rs.getString("categorie");
                auteur = rs.getString("auteur");
                description = rs.getString("description");
                prix = rs.getInt("prix");
                stock = rs.getInt("stock");
                
                Object[] clt = {id, nomlivre, categorie, auteur, description, prix, stock};
                dt.addRow(clt);
                System.out.println("Nombre Total de Livres : " + nTotal);
              
            }
            // TableEpl.setModel(dt);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erreur d'afficher la liste des clients\n" + e.getMessage());
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
